# Generated by Django 4.2 on 2023-06-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0009_rename_id_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
