# Generated by Django 4.2 on 2023-06-14 16:44

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0010_rename_product_id_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avif_image',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, default=1, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='product_image/'),
            preserve_default=False,
        ),
    ]
