# Generated by Django 4.2 on 2023-06-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0012_remove_product_avif_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Каталог'},
        ),
    ]
