# Generated by Django 4.2 on 2023-06-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0013_alter_product_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductCatalog',
        ),
    ]
