# Generated by Django 4.2 on 2023-06-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0015_productcatalog_description_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
    ]
