# Generated by Django 4.2 on 2023-06-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0017_productimage_alter_productcatalog_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='images',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
