# Generated by Django 4.2 on 2023-06-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0020_remove_productcatalog_images_productcatalog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Brand.productcatalog')),
            ],
        ),
    ]
