# Generated by Django 4.2 on 2023-06-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0021_alter_productcatalog_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Розміри в наявності'),
        ),
    ]
