# Generated by Django 4.2 on 2023-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0022_remove_productcatalog_image_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Скидка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='description_detail',
            field=models.TextField(verbose_name='Детальний опис'),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
    ]
