# Generated by Django 4.2 on 2023-06-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0023_productcatalog_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Скидка'),
        ),
    ]
