# Generated by Django 4.2 on 2023-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0025_alter_image_image_alter_productcatalog_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='description',
            field=models.CharField(max_length=30, verbose_name='Магазин'),
        ),
    ]
