# Generated by Django 4.2 on 2023-06-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0026_alter_productcatalog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='description',
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='description_prefix',
            field=models.CharField(default='©', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='shop_name',
            field=models.CharField(default=0, max_length=27, verbose_name='Магазин'),
            preserve_default=False,
        ),
    ]
