# Generated by Django 4.2 on 2023-09-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0030_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
