# Generated by Django 4.2 on 2023-09-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0033_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
